# Generated by Django 3.1 on 2021-11-14 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('m1', models.CharField(max_length=200)),
                ('m2', models.CharField(blank=True, max_length=200)),
                ('m3', models.CharField(blank=True, max_length=200)),
                ('m4', models.CharField(blank=True, max_length=200)),
                ('m5', models.CharField(blank=True, max_length=200)),
                ('m6', models.CharField(blank=True, max_length=200)),
                ('m7', models.CharField(blank=True, max_length=200)),
                ('m8', models.CharField(blank=True, max_length=200)),
                ('m9', models.CharField(blank=True, max_length=200)),
                ('m10', models.CharField(blank=True, max_length=200)),
                ('m11', models.CharField(blank=True, max_length=200)),
                ('m12', models.CharField(blank=True, max_length=200)),
                ('m13', models.CharField(blank=True, max_length=200)),
                ('m14', models.CharField(blank=True, max_length=200)),
                ('m15', models.CharField(blank=True, max_length=200)),
                ('m16', models.CharField(blank=True, max_length=200)),
                ('m17', models.CharField(blank=True, max_length=200)),
                ('m18', models.CharField(blank=True, max_length=200)),
                ('m19', models.CharField(blank=True, max_length=200)),
                ('m20', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='script',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='script',
            name='entity',
            field=models.ManyToManyField(blank=True, to='intake.Entity'),
        ),
        migrations.AddField(
            model_name='script',
            name='issue',
            field=models.ManyToManyField(blank=True, to='intake.Issue'),
        ),
        migrations.AddField(
            model_name='script',
            name='keyword',
            field=models.ManyToManyField(blank=True, to='intake.Keyword'),
        ),
        migrations.AlterField(
            model_name='move',
            name='quote',
            field=models.CharField(max_length=500),
        ),
    ]
