# Generated by Django 3.1 on 2021-11-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20211114_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='emergency',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], default='n', max_length=1),
        ),
        migrations.AddField(
            model_name='move',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
