version: '3.8'

services:
   web:
    build:
      context: .
      dockerfile: Dockerfile
    image: 964215444155.dkr.ecr.us-east-1.amazonaws.com/intake-tool-ec2:web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev

volumes:
  postgres_data:
  static_volume:
  media_volume:
