# Generated by Django 3.1 on 2021-11-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0004_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=200)),
                ('issue', models.ManyToManyField(blank=True, to='intake.Issue')),
                ('keyword', models.ManyToManyField(blank=True, to='intake.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('a', 'active'), ('i', 'inactive'), ('h', 'hiatus'), ('u', 'unknown')], default='u', max_length=1)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('area', models.ManyToManyField(blank=True, to='intake.Area')),
                ('msc_group', models.ManyToManyField(blank=True, to='intakemanager.MSCGroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
