# Generated by Django 3.1 on 2021-11-28 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intakemanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeuser',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intakeuser',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
