from django.urls import path
from .views import BookListView, PlantListView, StrainDetailView, TTInventoryDetailView, TTLocationDetailView, TTPlantBatchDetailView, TTPlantBatchHarvestDetailView, TTProductBatchDetailView, TTSublotDetailView, TTStorageBatchDetailView, TTLabSampleDetailView, TTStorageBatchCreateView, PlantDetailView, WeightDetailView, DerivativeDetailView, PlantHarvestDetailView, LabResultDetailView, LabSampleResultDetailView, LabSampleDetailView, InventoryDetailView, InventoryRoomDetailView, InventorySublotDetailView, InventoryMoveDetailView, PlantCureDetailView, InvoiceInventoryDetailView, InvoiceModelDetailView, ManifestDriverDetailView, StopItemDetailView, ManifestStopDetailView, ManifestVehicleDetailView, ManifestThirdPartyTransporterDetailView, ManifestDetailView, GrowRoomDetailView

urlpatterns = [ 
    path('', BookListView.as_view(), name='book_list'),
    path('', PlantListView.as_view(), name='plant_list'),
    path('strain/<str:pk>',
         StrainDetailView.as_view(), name='strain_detail'),
    path('tt_inventory/<str:pk>',
         TTInventoryDetailView.as_view(), name='tt_inventory_detail'),
    path('tt_location/<str:pk>',
         TTLocationDetailView.as_view(), name='tt_location_detail'),
    path('tt_plant_batch/<str:pk>',
         TTPlantBatchDetailView.as_view(), name='tt_plant_batch_detail'),
    path('tt_plant_batch_harvest/<str:pk>',
         TTPlantBatchHarvestDetailView.as_view(), name='tt_plant_batch_harvest_detail'),
    path('tt_product_batch/<str:pk>',
         TTProductBatchDetailView.as_view(), name='tt_product_batch_detail'),
    path('tt_storage_batch/<str:pk>',
         TTStorageBatchDetailView.as_view(), name='tt_storage_batch_detail'),
    path('tt_sublot/<str:pk>',
         TTSublotDetailView.as_view(), name='tt_sublot_detail'),
    path('tt_lab_sample/<str:pk>',
         TTLabSampleDetailView.as_view(), name='tt_lab_sample_detail'),
    path('plant/<str:pk>',
         PlantDetailView.as_view(), name='plant_detail'),
    path('weight/<str:pk>',
         WeightDetailView.as_view(), name='weight_detail'),
    path('derivative/<str:pk>',
         DerivativeDetailView.as_view(), name='derivative_detail'),
    path('plant_harvest/<str:pk>',
         PlantHarvestDetailView.as_view(), name='plant_harvest_detail'),
    path('lab_result/<str:pk>',
         LabResultDetailView.as_view(), name='lab_result_detail'),
    path('lab_sample_result/<str:pk>',
         LabSampleResultDetailView.as_view(), name='lab_sample_result_detail'),
    path('lab_sample/<str:pk>',
         LabSampleDetailView.as_view(), name='lab_sample_detail'),
    path('inventory/<str:pk>',
         InventoryDetailView.as_view(), name='inventory_detail'),
    path('inventory_room/<str:pk>',
         InventoryRoomDetailView.as_view(), name='inventory_room_detail'),
    path('inventory_sublot/<str:pk>',
         InventorySublotDetailView.as_view(), name='inventory_sublot_detail'),
    path('inventory_move/<str:pk>',
         InventoryMoveDetailView.as_view(), name='inventory_move_detail'),
    path('plant_cure/<str:pk>',
         PlantCureDetailView.as_view(), name='plant_cure_detail'),
    path('invoice_inventory/<str:pk>',
         InvoiceInventoryDetailView.as_view(), name='invoice_inventory_detail'),
    path('invoice_model/<str:pk>',
         InvoiceModelDetailView.as_view(), name='invoice_model_detail'),
    path('manifest_driver/<str:pk>',
         ManifestDriverDetailView.as_view(), name='manifest_driver_detail'),
    path('stop_item/<str:pk>',
         StopItemDetailView.as_view(), name='stop_item_detail'),
    path('manifest_stop/<str:pk>',
         ManifestStopDetailView.as_view(), name='manifest_stop_detail'),
    path('manifest_vehicle/<str:pk>',
         ManifestVehicleDetailView.as_view(), name='manifest_vehicle_detail'),
    path('manifest_thirdpartytransporter/<str:pk>',
         ManifestThirdPartyTransporterDetailView.as_view(), name='manifest_thirdpartytransporter_detail'),
    path('manifest/<str:pk>',
         ManifestDetailView.as_view(), name='manifest_detail'),
    path('grow_room/<str:pk>',
         GrowRoomDetailView.as_view(), name='grow_room_detail'),

    path('tt_storage_batch/create/',  
          TTStorageBatchCreateView.as_view(), name='tt_storage_batch_create'),
    

]